add debian support

diff --git a/run_once_init.sh.tmpl b/run_once_init.sh.tmpl
--- a/run_once_init.sh.tmpl
+++ b/run_once_init.sh.tmpl
@@ -14,6 +14,16 @@ if ! which ansible ; then
     sudo apt-get install -y software-properties-common
     sudo apt-add-repository --yes --update ppa:ansible/ansible
     sudo apt-get install -y ansible
+{{ else if eq .chezmoi.osRelease.id "debian" -}}
+    if ! grep -q ansible /etc/apt/sources.list ; then
+        echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee --append /etc/apt/sources.list
+    fi
+    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
+    sudo apt update
+    sudo apt install ansible
+{{ else -}}
+    echo "Unable to install ansible, please install manually!"
+    exit 1
 {{ end -}}
 {{ else if eq .chezmoi.os "darwin" -}}
     brew install ansible
